### ISSUE TITLE
SML Parser Problem

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/LoxBerry-Plugin-Smartmeter#12]
Siehe https://github.com/Woersty/LoxBerry-Plugin-SML-eMon/issues/2

**Comment by mschlenstedt** [comment]
Eventuell Umstellung auf https://github.com/Apollon77/smartmeter-obis

Das scheint gepflegt zu werden.

**Comment by mschlenstedt** [comment]
Oder besser gleich vzlogger: https://raspberry.tips/raspberrypi-tutorials/smartmeter-stromzaehler-mit-dem-raspberry-pi-auslesen-und-aufzeichnen

**Comment by blacksun80** [comment]
Kann geschlossen, werden wenn mein PullRequest https://github.com/mschlenstedt/LoxBerry-Plugin-Smartmeter/pull/15 übernommen wird.
