### ISSUE TITLE
Please add new counter. IskraMT382

### ISSUE THREAD

**Issue by gmkey** [mschlenstedt/LoxBerry-Plugin-Smartmeter#13]
On my RPi3 I've hacked the following counter into the sm_logger.pl, but I'm not sure if this is correct (what is the difference between baudrate and startbaudrate?

Could you please add it? Second question: are you planning to upgrade the plugin to the new gui format (as I would love to make a dutch translation.) 

elsif ( $protocol eq "iskraMT382d0" ) {

	### Defaults
	our $baudrate = 9600 if !$baudrate;
	our $startbaudrate = 9600 if !$startbaudrate;
	our $databits = 7 if !$databits;
	our $stopbits = 1 if !$stopbits;
	our $parity = "even" if !$parity;
	our $handshake = "none" if !$handshake;
	our $timeout = "10" if !$timeout;
	our $delay = "2" if !$delay;
	our $preinitcommand = "";
	our $precommand = "";
	our $postcommand = "";

	&PROTO_GENERICD0;
}

**Comment by blacksun80** [comment]
Kann geschlossen, werden wenn mein PullRequest https://github.com/mschlenstedt/LoxBerry-Plugin-Smartmeter/pull/15 übernommen wird.
