### ISSUE TITLE
Einspeisewert wird nicht geliefert bei ED300L

### ISSUE THREAD

**Issue by wil76** [mschlenstedt/LoxBerry-Plugin-Smartmeter#14]

**Comment by wil76** [comment]
> No description provided.

 mein Weidmann Lesekopf liefert lt. emlog unter 1.7.0 jeweils einen positiven oder negativen Wert, abhängig davon ob Strom bezogen oder eingespeist wird.
der Loxberry liefrt unter 1.7.0 aber immer 0.
lediglich, wenn ich Strom beziege sehe ich unter OBIS_1.99.0 den entspr. Wert.
ich bräuchte aber unbedingt den aktuell überschüssigen Wert.

**Comment by wil76** [comment]
irrtümlich geschlossen

**Comment by blacksun80** [comment]
Kann geschlossen, werden wenn mein PullRequest übernommen wird.
