### ISSUE TITLE
.DUMP file empty

### ISSUE THREAD

**Issue by ww00001** [mschlenstedt/LoxBerry-Plugin-Smartmeter#20]
Hello everyone, thanks for your work. 
I try to read out from Landis+Gyr E650 and no data is written to the .dump file, so no data is parsed. 
But if I do "cat /dev/ttyUSB1" I get all the output. 
Any idea where to search for the bug? I had to increase the delay to see all information while doing a "cat"

Settings:
`[_SN_]
STOPBITS=1
PROTOCOL=genericd0
HANDSHAKE=none
DEVICE=/dev/serial/smartmeter/_SN_
TIMEOUT=5
DELAY=260
PARITY=even
DATABITS=7
BAUDRATE=9600
NAME=Solaranlage
STARTBAUDRATE=300
METER=manual
SERIAL=_SN_`

**Comment by blacksun80** [comment]
Please create a thread for your problem here.

[https://www.loxforum.com/forum/projektforen/loxberry/plugins/85702-neues-plugin-smartmeter-stromz%C3%A4hler-auslesen/page33](url)
