### ISSUE TITLE
Setting up port /dev/serial/by-id/usb... Permission denied. Giving up.

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/LoxBerry-Plugin-Smartmeter#4]
Setting up port /dev/serial/by-id/usb-Silicon_Labs_CP2104_USB_to_UART_Bridge_Controller_0072D0B2-if00-port0: Baudrate:9600/9600 Databits:8 Stopbits:1 Parity:none Handshake:none
Can't open /dev/serial/by-id/usb-Silicon_Labs_CP2104_USB_to_UART_Bridge_Controller_0072D0B2-if00-port0: Permission denied. Giving up.

**Comment by Woersty** [comment]
Workaround
` chmod 777 /dev/serial/by-id/usb-Silicon_Labs_CP2104_USB_to_UART_Bridge_Controller_* `

Müsste dann später mal ins root installscript mit rein.

**Comment by mschlenstedt** [comment]
Bei mir stimmen die Berechtigungen:

loxberry@loxberry:~/development $ ls -l /dev/serial/by-id/usb-Silicon_Labs_CP2104_USB_to_UART_Bridge_Controller_0092*
lrwxrwxrwx 1 root root 13 Feb  5 14:33 /dev/serial/by-id/usb-Silicon_Labs_CP2104_USB_to_UART_Bridge_Controller_0092C360-if00-port0 -> ../../ttyUSB0
lrwxrwxrwx 1 root root 13 Feb 18 13:54 /dev/serial/by-id/usb-Silicon_Labs_CP2104_USB_to_UART_Bridge_Controller_0092D106-if00-port0 -> ../../ttyUSB1
loxberry@loxberry:~/development $

**Comment by mschlenstedt** [comment]
Da das Plugin bei vielen jetzt anscheinend läuft mach ich das mal zu.
