### ISSUE TITLE
Sporadisch keine Daten

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/LoxBerry-Plugin-Smartmeter#5]
In der PHP Klasse den Datenstrom auf Anfang und Ende beschneiden.

(Übernehme ich.)

**Comment by mschlenstedt** [comment]
Hi,

habe jetzt alle anderen Änderungen drin. Wenn die SML-Geschichte korrigiert ist, veröffentliche ich Version 0.1

**Comment by Woersty** [comment]
Habe ich schon gemacht nur liegt es daran nicht. 
Leider kann ich dir noch keine Lösung anbieten.
Schaue es mir ab nächste Woche nochmal an.
Oh - sind ja nur noch 2 Minuten 🤣 
Aber eher ab Montag Abend

**Comment by mschlenstedt** [comment]
Ok - mach Dir keinen Stress. Ansonsten haue ich eine erste Version erst einmal so raus. Testen kann man ja auch mit dem aktuellen Stand.

Brauche aber selbst auch noch ein paar Tage für das Wiki...

**Comment by mschlenstedt** [comment]
Ich schließe das mal. Bisher gab's im Forum keine Rückmeldungen dazu.
