### ISSUE TITLE
Weitere Werte für Gaszähler aufnehmen

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/LoxBerry-Plugin-Smartmeter#8]
Hi alle,
super, dass es jetzt ein Profil für den "Siemens UH50" gibt. Endlich kann ich meine Fernwärmestation auslesen. Wie ich in den Dateien "sm_logger.pl" und in der "show.cgi" nachvollziehen konnte, werden aber - zumindest in meinem Fall - nicht alle relevanten Werte (korrekt) berücksichtigt, sodass lediglich die maximale Heizleistung (Wert 6.6) und die Betriebsstunden (Wert 6.31) über das Plugin zu Loxone geschoben werden, auch wenn alle anderen relevanten Daten eigentlich vorher korrekt eingelesen wurden. So sieht das Log in Loxberry dazu aus:

AH06GHPU: Found configuration for AH06GHPU
AH06GHPU: Presetting: siemensuh50do.
Initial Baudrate: 300
Max Baudrate: 2400
Protocol: siemensuh50do
Timeout: 10
Delay: 1
Setting up port /dev/serial/smartmeter/AH06GHPU: Baudrate:2400/300 Databits:7 Stopbits:1 Parity:even Handshake:none
Sending D0 Starting Sequence
Send: 
20 Bytes written.
Send: /?!
5 Bytes written.
Changing Baudrate to 2400
Send: 030
6 Bytes written.
/LUGCUH50}6.8(0015.664*MWh)6.26(00793.54*m3)9.21(68 660570) 
6.26*01(00527.94*m3)6.8*01(0009.350*MWh) 
F(0)9.20(68660570)6.35(60*m) 
6.6(0014.7*kW)6.6*01(0014.3*kW)6.33(000.576*m3ph)9 .4(149.4*C&070.6*C) 
6.31(0019952*h)6.32(0000008*h)9.22(R)9.6(000&68660 570&0&000&68660570&0) 
9.7(20000)6.32*01(0000003*h)6.36(01-01&00:00)6.33*01(000.576*m3ph) 
6.8.1()6.8.2()6.8.3()6.8.4()6.8.5() 
6.8.1*01()6.8.2*01()6.8.3*01() 
6.8.4*01()6.8.5*01() 
9.4*01(149.4*C&070.4*C) 
6.36.1(2018-02-28)6.36.1*01(2017-11-13) 
6.36.2(2017-02-27)6.36.2*01(2017-02-27) 
6.36.3(2016-03-17)6.36.3*01(2016-03-17) 
6.36.4(2018-02-26)6.36.4*01(2017-04-20) 
6.36.5()6.36*02(01&00:00)9.36(2018-06-26&11:50:18)9.24(0.6*m3ph) 
9.17(0)9.18()9.19()9.25() 
9.1(0&1&0&0000&CECV&CECV&1&5.22&5.22&F&101008&1>1> 04&08&0&00&:5&00&20) 
9.2(&&)9.29()9.31(0005672*h) 
9.0.1(00000000)9.0.2(00000000)9.34.1(000.00000*m3) 9.34.2(000.00000*m3) 
8.26.1(00000000*m3)8.26.2(00000000*m3) 
8.26.1*01(00000000*m3)8.26.2*01(00000000*m3) 
6.26.1()6.26.4()6.26.5() 
6.26.1*01()6.26.4*01()6.26.5*01()0.0(68660570) 
! 
n
Save raw buffer to /var/run/shm/smartmeter/AH06GHPU.dump
Parse /var/run/shm/smartmeter/AH06GHPU.dump as D0-Protocol.
Calculate average power for cons.
Last Reading: . Saved before: 425002.8650 hours. Consumption: 0.0000. Avg. Power: 0.0000,
Calculate average power for del.
Last Reading: . Saved before: 425002.8650 hours. Consumption: 0.0000. Avg. Power: 0.0000,
Save Meter data to /var/run/shm/smartmeter/AH06GHPU.data.
All data written to /var/run/shm/smartmeter/AH06GHPU.xxxx
AH06GHPU: UDP String to send: AH06GHPU:Last_Update:2018-06-26 12:51:54; AH06GHPU:Last_UpdateLoxEpoche:299249514; AH06GHPU:Consumption_Total_OBIS_6.8.0:; AH06GHPU:Consumption_Tarif1_OBIS_6.8.1:; AH06GHPU:Consumption_Tarif2_OBIS_6.8.2:; AH06GHPU:Consumption_Tarif3_OBIS_6.8.3:; AH06GHPU:Consumption_Tarif4_OBIS_6.8.4:; AH06GHPU:Consumption_Tarif5_OBIS_6.8.5:; AH06GHPU:Consumption_Tarif6_OBIS_6.8.6:; AH06GHPU:Consumption_Tarif7_OBIS_6.8.7:; AH06GHPU:Consumption_Tarif8_OBIS_6.8.8:; AH06GHPU:Consumption_Tarif9_OBIS_6.8.9:; AH06GHPU:Consumption_CalculatedPower_OBIS_1.99.0:0 .0000; AH06GHPU:Max_Power_OBIS_6.6.0:0014.7; AH06GHPU:Volume_OBIS_6.26.0:; AH06GHPU:Hour_OBIS_6.31.0:0019952; AH06GHPU:Hour_OBIS_6.32.0:; AH06GHPU:Hour_OBIS_9.31.0:; AH06GHPU:Flow_OBIS_6.33.0:; 
AH06GHPU: Send Data to Hall at 192.168.3.5.

Relevante Werte wären also weiterhin (von denen ich weiss):
-6.8 -> Zählerstand MWh
-6.26 -> Durchlauf m3
-6.33 -> max. Durchlauf m3/h
-9.4 -> max. Vorlauf und Rücklauf (jeweils in °C)
-6.32 -> Fehlstunden
-9.31 -> "Flowhours"

Evtl. könnte das jemand im Plugin "geradeziehen" bzw. erweitern? Ich würde ja selbst Hand anlegen, aber bis ich das hingefrickelt bekomme...

Grüße und danke schon mal
Jörg

**Comment by mschlenstedt** [comment]
Siehe auch #11

**Comment by chiefjoejj** [comment]
Gerade mal wieder meine Zähler per Loxberry und "SmartMeter"-Plugin eingebunden. Mein hier aus 2018 mitgeteiltes Issue ist leider immer noch nicht behoben in V1.1 vom Sept 2019. Die Werte meines Fernwärmezählers T550 kann ich deshalb nicht nutzen (Problem von oben). Besteht die Chance, dass das noch gefixt wird?

Viele Grüße
Jörg

**Comment by blacksun80** [comment]
> 
> 
> Gerade mal wieder meine Zähler per Loxberry und "SmartMeter"-Plugin eingebunden. Mein hier aus 2018 mitgeteiltes Issue ist leider immer noch nicht behoben in V1.1 vom Sept 2019. Die Werte meines Fernwärmezählers T550 kann ich deshalb nicht nutzen (Problem von oben). Besteht die Chance, dass das noch gefixt wird?
> 
> Viele Grüße
> Jörg

Hallo Jörg, kannst du mir dazu mal ein dump File schicken? Dann schau ich mir das mal an.

**Comment by chiefjoejj** [comment]
Hi Michael,
hier ist der Dump:

/LUGCUH506.8(0028.646*MWh)6.26(01332.36*m3)9.21(68660570)
6.26*01(01325.66*m3)6.8*01(0028.415*MWh)
F(0)9.20(68660570)6.35(60*m)
6.6(0018.5*kW)6.6*01(0018.5*kW)6.33(000.576*m3ph)9.4(149.4*C&075.9*C)
6.31(0033355*h)6.32(0000009*h)9.22(R)9.6(000&68660570&0&000&68660570&0)
9.7(20000)6.32*01(0000009*h)6.36(01-01&00:00)6.33*01(000.576*m3ph)
6.8.1()6.8.2()6.8.3()6.8.4()6.8.5()
6.8.1*01()6.8.2*01()6.8.3*01()
6.8.4*01()6.8.5*01()
9.4*01(149.4*C&075.9*C)
6.36.1(2018-11-20)6.36.1*01(2018-11-20)
6.36.2(2017-02-27)6.36.2*01(2017-02-27)
6.36.3(2016-03-17)6.36.3*01(2016-03-17)
6.36.4(2018-11-21)6.36.4*01(2018-11-21)
6.36.5()6.36*02(01&00:00)9.36(2020-01-05&22:20:35)9.24(0.6*m3ph)
9.17(0)9.18()9.19()9.25()
9.1(0&1&0&0000&CECV&CECV&1&5.22&5.22&F&101008&1>1>04&08&0&00&:5&00&20)
9.2(&&)9.29()9.31(0009497*h)
9.0.1(00000000)9.0.2(00000000)9.34.1(000.00000*m3)9.34.2(000.00000*m3)
8.26.1(00000000*m3)8.26.2(00000000*m3)
8.26.1*01(00000000*m3)8.26.2*01(00000000*m3)
6.26.1()6.26.4()6.26.5()
6.26.1*01()6.26.4*01()6.26.5*01()0.0(68660570)
!
e

Viele Grüße und danke für deine Hilfe
Jörg

**Comment by blacksun80** [comment]
Servus Jörg, bitte die dump Datei. Pfad /dev/shm/smartmeter/serial.dump.

Mit dieser Datei kann ich es bei mir simulieren.

Von: chiefjoejj <notifications@github.com>
Gesendet: Mittwoch, 8. Januar 2020 10:42
An: mschlenstedt/LoxBerry-Plugin-Smartmeter <LoxBerry-Plugin-Smartmeter@noreply.github.com>
Cc: blacksun80 <kaufmann-michael@outlook.com>; Comment <comment@noreply.github.com>
Betreff: Re: [mschlenstedt/LoxBerry-Plugin-Smartmeter] Weitere Werte für Gaszähler aufnehmen (#8)


Hi Michael,
hier ist der Dump:

/LUGCUH50�������6.8(0028.646MWh)6.26(01332.36m3)9.21(68660570)
6.2601(01325.66m3)6.801(0028.415MWh)
F(0)9.20(68660570)6.35(60m)
6.6(0018.5kW)6.601(0018.5kW)6.33(000.576m3ph)9.4(149.4C&075.9C)
6.31(0033355h)6.32(0000009h)9.22(R)9.6(000&68660570&0&000&68660570&0)
9.7(20000)6.3201(0000009h)6.36(01-01&00:00)6.3301(000.576m3ph)
6.8.1()6.8.2()6.8.3()6.8.4()6.8.5()
6.8.101()6.8.201()6.8.301()
6.8.401()6.8.501()
9.401(149.4C&075.9C)
6.36.1(2018-11-20)6.36.101(2018-11-20)
6.36.2(2017-02-27)6.36.201(2017-02-27)
6.36.3(2016-03-17)6.36.301(2016-03-17)
6.36.4(2018-11-21)6.36.401(2018-11-21)
6.36.5()6.3602(01&00:00)9.36(2020-01-05&22:20:35)9.24(0.6m3ph)
9.17(0)9.18()9.19()9.25()
9.1(0&1&0&0000&CECV&CECV&1&5.22&5.22&F&101008&1>1>04&08&0&00&:5&00&20)
9.2(&&)9.29()9.31(0009497h)
9.0.1(00000000)9.0.2(00000000)9.34.1(000.00000m3)9.34.2(000.00000m3)
8.26.1(00000000m3)8.26.2(00000000m3)
8.26.101(00000000m3)8.26.201(00000000m3)
6.26.1()6.26.4()6.26.5()
6.26.101()6.26.401()6.26.5*01()0.0(68660570)
!
�e�

Viele Grüße und danke für deine Hilfe
Jörg

**Comment by chiefjoejj** [comment]
Hi Michael,

das sind alle Dateien, die in dem Verzeichnis sind. Eine serial.dump war nicht mit dabei….

**Comment by chiefjoejj** [comment]
Hi Michael,
hier alle Dateien, die sich in dem Ordner befinden:
[https://meintechblog.de/download/smartmeter.zip](url)

Eine serial.dump war nicht mit dabei...

**Comment by blacksun80** [comment]
Hallo Jörg,

tausche diese Datei im Pfad /opt/loxberry/webfrontend/cgi/plugins/smartmeter/bin

aus.

Dann hast du schonmal

-6.32 -> Fehlstunden
-9.31 -> "Flowhours"
-6.26 -> Durchlauf m3
-6.33 -> max. Durchlauf m3/h

Teste mal.

Von: chiefjoejj <notifications@github.com>
Gesendet: Mittwoch, 8. Januar 2020 10:55
An: mschlenstedt/LoxBerry-Plugin-Smartmeter <LoxBerry-Plugin-Smartmeter@noreply.github.com>
Cc: blacksun80 <kaufmann-michael@outlook.com>; Comment <comment@noreply.github.com>
Betreff: Re: [mschlenstedt/LoxBerry-Plugin-Smartmeter] Weitere Werte für Gaszähler aufnehmen (#8)


Hi Michael,
hier alle Dateien, die sich in dem Ordner befinden:
https://meintechblog.de/download/smartmeter.zip<url>

Eine serial.dump war nicht mit dabei...

**Comment by blacksun80** [comment]
Passwort: test

Von: chiefjoejj <notifications@github.com>
Gesendet: Mittwoch, 8. Januar 2020 10:55
An: mschlenstedt/LoxBerry-Plugin-Smartmeter <LoxBerry-Plugin-Smartmeter@noreply.github.com>
Cc: blacksun80 <kaufmann-michael@outlook.com>; Comment <comment@noreply.github.com>
Betreff: Re: [mschlenstedt/LoxBerry-Plugin-Smartmeter] Weitere Werte für Gaszähler aufnehmen (#8)


Hi Michael,
hier alle Dateien, die sich in dem Ordner befinden:
https://meintechblog.de/download/smartmeter.zip<url>

Eine serial.dump war nicht mit dabei...

**Comment by blacksun80** [comment]
Hallo Jörg, anbei eine aktualisierte sm_logger.pl. Hier sind nun auch 

-6.8 -> Zählerstand MWh
-9.4 -> max. Vorlauf und Rücklauf (jeweils in °C)

dabei. Vorlauf und Rücklauf in einer extra Variable. Da ich keine Liste mit den OBIS Kennzahlen habe, die für diesen Zähler passen, kann ich die restlichen OBIS Kennzahlen nicht interpretieren. 

Wenn du noch weitere brauchst, schreibs mir einfach nochmal.

Teste es mal, wenn du Zeit hast. 

[sm_logger.zip](https://github.com/mschlenstedt/LoxBerry-Plugin-Smartmeter/files/4036572/sm_logger.zip)

**Comment by chiefjoejj** [comment]
Hi Michael,
vielen Dank für deine Mühen!
Hab die Datei ausgetauscht, die Berechtigung auf 755 gesetzt und Loxberry neugestartet.
Jetzt bekomme ich immer nur "ID_VON_IR_ZAEHLER: No data found" an Loxone übermittelt.

In der fetch_manually.log steht bspw:
"A506KKWI: Found configuration for A506KKWI
A506KKWI: Presetting: landisgyre350d0.
A506KKWI: UDP String to send: A506KKWI: No data found
A506KKWI: Send Data to Hall at 192.168.3.5.
A506KKWI: Send OK to Hall. IP:192.168.3.5 Port:7003
AH06GHPU: Found configuration for AH06GHPU
AH06GHPU: Presetting: landisgyret550d0.
AH06GHPU: UDP String to send: AH06GHPU: No data found
AH06GHPU: Send Data to Hall at 192.168.3.5.
AH06GHPU: Send OK to Hall. IP:192.168.3.5 Port:7003"

**Comment by blacksun80** [comment]
Probiere mal die von meinem vorletzten Post mit Passwort: test.

Diese sm_logger.pl habe ich zu Hause noch getestet. Da hats noch funktioniert.

**Comment by blacksun80** [comment]
Schon getestet?

**Comment by blacksun80** [comment]
> Hi Michael,
> vielen Dank für deine Mühen!
> Hab die Datei ausgetauscht, die Berechtigung auf 755 gesetzt und Loxberry neugestartet.
> Jetzt bekomme ich immer nur "ID_VON_IR_ZAEHLER: No data found" an Loxone übermittelt.
> 
> In der fetch_manually.log steht bspw:
> "A506KKWI: Found configuration for A506KKWI
> A506KKWI: Presetting: landisgyre350d0.
> A506KKWI: UDP String to send: A506KKWI: No data found
> A506KKWI: Send Data to Hall at 192.168.3.5.
> A506KKWI: Send OK to Hall. IP:192.168.3.5 Port:7003
> AH06GHPU: Found configuration for AH06GHPU
> AH06GHPU: Presetting: landisgyret550d0.
> AH06GHPU: UDP String to send: AH06GHPU: No data found
> AH06GHPU: Send Data to Hall at 192.168.3.5.
> AH06GHPU: Send OK to Hall. IP:192.168.3.5 Port:7003"

Schon getestet?

**Comment by chiefjoejj** [comment]
Hi,
jetzt bin ich endlich dazu gekommen.

Wenn ich http://loxberry/plugins/smartmeter/index.php aufrufe, werden mir alle Werte ausgelesenen Werte korrekt angezeigt:

A506KKWI:Last_Update:2020-01-10 20:02:52
A506KKWI:Last_UpdateLoxEpoche:347918572
A506KKWI:Consumption_Total_OBIS_1.8.0:015668.397
A506KKWI:Consumption_Tarif1_OBIS_1.8.1:015668.397
A506KKWI:Consumption_Tarif2_OBIS_1.8.2:000000.000
A506KKWI:Consumption_Tarif3_OBIS_1.8.3:
A506KKWI:Consumption_Tarif4_OBIS_1.8.4:
A506KKWI:Consumption_Tarif5_OBIS_1.8.5:
A506KKWI:Consumption_Tarif6_OBIS_1.8.6:
A506KKWI:Consumption_Tarif7_OBIS_1.8.7:
A506KKWI:Consumption_Tarif8_OBIS_1.8.8:
A506KKWI:Consumption_Tarif9_OBIS_1.8.9:
A506KKWI:Consumption_CalculatedPower_OBIS_1.99.0:3.5229
A506KKWI:Consumption_Power_OBIS_1.7.0:
A506KKWI:Consumption_Power_L1_OBIS_21.7.0:
A506KKWI:Consumption_Power_L2_OBIS_41.7.0:
A506KKWI:Consumption_Power_L3_OBIS_61.7.0:
A506KKWI:Delivery_Total_OBIS_2.8.0:000000.207
A506KKWI:Delivery_Tarif1_OBIS_2.8.1:000000.207
A506KKWI:Delivery_Tarif2_OBIS_2.8.2:000000.000
A506KKWI:Delivery_Tarif3_OBIS_2.8.3:
A506KKWI:Delivery_Tarif4_OBIS_2.8.4:
A506KKWI:Delivery_Tarif5_OBIS_2.8.5:
A506KKWI:Delivery_Tarif6_OBIS_2.8.6:
A506KKWI:Delivery_Tarif7_OBIS_2.8.7:
A506KKWI:Delivery_Tarif8_OBIS_2.8.8:
A506KKWI:Delivery_Tarif9_OBIS_2.8.9:
A506KKWI:Delivery_CalculatedPower_OBIS_2.99.0:0.0000
A506KKWI:Delivery_Power_OBIS_2.7.0:
A506KKWI:Total_Power_OBIS_15.7.0:
A506KKWI:Total_Power_OBIS_16.7.0:
#EOF

Beim übertragenen UDP-String besitzen die übertragenen OBIS-Kennzahlen jedoch keine Werte. Auch werden nicht alle Kennzahlen übertragen. Hat das einen speziellen Hintergrund? Cool wäre es, wenn einfach alle Kennzahlen inkl. Werte 1:1 übertragen werden bzw. alle Kennzahlen, die überhaupt einen Wert haben. Mit dem Rest kann man ja eh nichts anfangen...

Hier nochmal die Dateien des smartmeter-Verzeichnisses: https://meintechblog.de/download/smartmeter_2.zip

Grüße
Jörg

**Comment by blacksun80** [comment]
Das verstehe ich jetzt aber nicht. Ich bin jetzt eigentlich von dem Zähler AH06GPU ausgegangen. Das ist der Wärmemengenzähler. Laut dem fetch_manual.log hat dieser Zähler aber keine Daten ausgegeben. Also kann er auch nichts an Loxone verschicken.

`A506KKWI: UDP String to send: A506KKWI:Last_Update:2020-01-10 20:02:52; A506KKWI:Last_UpdateLoxEpoche:347918572; A506KKWI:Consumption_Total_OBIS_1.8.0:015668.397; A506KKWI:Consumption_Tarif1_OBIS_1.8.1:015668.397; A506KKWI:Consumption_Tarif2_OBIS_1.8.2:000000.000; A506KKWI:Consumption_Tarif3_OBIS_1.8.3:; A506KKWI:Consumption_Tarif4_OBIS_1.8.4:; A506KKWI:Consumption_Tarif5_OBIS_1.8.5:; A506KKWI:Consumption_Tarif6_OBIS_1.8.6:; A506KKWI:Consumption_Tarif7_OBIS_1.8.7:; A506KKWI:Consumption_Tarif8_OBIS_1.8.8:; A506KKWI:Consumption_Tarif9_OBIS_1.8.9:; A506KKWI:Consumption_CalculatedPower_OBIS_1.99.0:3.5229; A506KKWI:Consumption_Power_OBIS_1.7.0:; A506KKWI:Consumption_Power_L1_OBIS_21.7.0:; A506KKWI:Consumption_Power_L2_OBIS_41.7.0:; A506KKWI:Consumption_Power_L3_OBIS_61.7.0:; A506KKWI:Delivery_Total_OBIS_2.8.0:000000.207; A506KKWI:Delivery_Tarif1_OBIS_2.8.1:000000.207; A506KKWI:Delivery_Tarif2_OBIS_2.8.2:000000.000; A506KKWI:Delivery_Tarif3_OBIS_2.8.3:; A506KKWI:Delivery_Tarif4_OBIS_2.8.4:; A506KKWI:Delivery_Tarif5_OBIS_2.8.5:; A506KKWI:Delivery_Tarif6_OBIS_2.8.6:; A506KKWI:Delivery_Tarif7_OBIS_2.8.7:; A506KKWI:Delivery_Tarif8_OBIS_2.8.8:; A506KKWI:Delivery_Tarif9_OBIS_2.8.9:; A506KKWI:Delivery_CalculatedPower_OBIS_2.99.0:0.0000; A506KKWI:Delivery_Power_OBIS_2.7.0:; A506KKWI:Total_Power_OBIS_15.7.0:; A506KKWI:Total_Power_OBIS_16.7.0:; 
A506KKWI: Send Data to Hall at 192.168.3.5.
A506KKWI: Send OK to Hall. IP:192.168.3.5 Port:7003
AH06GHPU: Found configuration for AH06GHPU
AH06GHPU: Presetting: landisgyret550d0.
Initial Baudrate: 300
Max Baudrate: 2400
Protocol: landisgyret550d0
Timeout: 10
Delay: 1
Setting up port /dev/serial/smartmeter/AH06GHPU: Baudrate:2400/300 Databits:7 Stopbits:1 Parity:even Handshake:none
Sending D0 Starting Sequence
Send:                     
20 Bytes written.
Send: /?!
5 Bytes written.
Changing Baudrate to 2400
Send: 030
6 Bytes written.
**DA FEHLT HIER DIE ANTWORT VOM ZÄHLER**
Save raw buffer to /var/run/shm/smartmeter/AH06GHPU.dump`

Der Zähler mit der Serialnummer A506KKWI ist dein Stromzähler. 
Diese Werte werden nicht per UDP übertragen habe ich gerade festgestellt. Sind also zwei Baustellen. 
Welcher dieser fehlenden Werte willst du noch haben bzw. welche sind für dich interessant. Dann schau ich da auch noch drüber. 

`/LGZ4ZMF100AC.M27
F.F(00)
C.1.0(32754814)
0.0(001LGZ0032754814)
C.1.1(        )
1.8.2(000000.000*kWh)
15.8.0(015668.604*kWh)
C.7.0(0013)
32.7(234*V)
52.7(237*V)
72.7(236*V)
C.5.0(0400)
0.2.0(M27)
0.2.8(FD25)
16.7(003.476*kW)`

Aber teste bitte nochmal den Wärmemengenzähler. Ich habe mich eigentlich jetzt erst auf diesen konzentriert, da in Post 1 angegeben ist, welche OBIS Werte vom Wärmemengenzähler fehlen.

Gruß
Michael

**Comment by blacksun80** [comment]
Hier noch die zusätzlichen OBIS Werte des Stromzählers.

Folgende zusätzliche OBIS Werte müssten jetzt auch vom Stromzähler per UDP übertragen werden.
16.7
32.7
52.7
72.7
[sm_logger.zip](https://github.com/mschlenstedt/LoxBerry-Plugin-Smartmeter/files/4047779/sm_logger.zip)

**Comment by blacksun80** [comment]
Servus Jörg, wie schauts aus? Funktionierts jetzt mit den letzten Änderungen in der sm_logger?
